name: Tests
on:
  pull_request:
  push:
    branches: [ '*.x' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Install dependencies
      run: composer install
    - name: Upload artifact
      uses: actions/upload-artifact@v4
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Download artifact
      uses: actions/download-artifact@v4
    - name: Lint
      run: composer run-script phpcs
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Download artifact
      uses: actions/download-artifact@v4
    - name: Unit tests
      run: composer run-script phpunit
